### PR TITLE
ran Makefile formatting command

### PR DESCRIPTION
**Pull request by cmgmyr**
make sure formatting is up to date

### CODE REVIEW

**Comment by jamesmills** [comment]
Why are we switching to use Symfony and not Laravel format?

**Comment by cmgmyr** [comment]
@jamesmills just following the rule preset in your [.php_cs](https://github.com/jamesmills/watchable/blob/master/.php_cs#L11) file. Unfortunately, the php-cs-fixer doesn't have a Laravel preset 😕

I think you could: 1) just stick with Symfony formatting or 2) go back to Laravel style, but only implement style CI and drop php-cs-fixer/Makefile

What do you think?

**Comment by jamesmills** [comment]
It's an interesting one. I am new to both so unsure what's best or most common practice. I will have a play and see. Thanks for your input.

**Comment by anthonysterling** [comment]
Either way, I'd probably drop Style CI and use Travis CI to run `make fix` or `make test` against submissions. This way you have a single source of truth, not to mention configuration, around what CS expectations your project has.

**Comment by jamesmills** [comment]
OK, going to remove Style CI and use Travis.

**Comment by jamesmills** [comment]
Hummmm, first time using Travis and not entirely sure how to set it up to run the tests. I will take another look at this later today.

**Comment by cmgmyr** [comment]
hey @jamesmills, you can take a look at my other repo [here](https://github.com/cmgmyr/laravel-messenger/blob/master/.travis.yml#L22) for a starting point.

**Comment by jamesmills** [comment]
Thanks @cmgmyr 

I managed to get something working. I have tidied up the style checking etc and tagged a 1.0.1 with all the clean code and stuff.

Thanks.

**Pull request closed without merging**
