### PR TITLE
Laravel 5.7 Compatibility

### PR DESCRIPTION
**Pull request by MadMikeyB**
Allow Package to be installed to Laravel 5.7

### CODE REVIEW

**Comment by jamesmills** [comment]
Thank you.

**Comment by MadMikeyB** [comment]
Hi @jamesmills, are you able to create a release for this? :)

**Comment by jamesmills** [comment]
Ah, sorry... doing now.

**Comment by jamesmills** [comment]
This is done. Should be tagged as 1.0.6

**Pull request merged**
